In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
def load_coffee_data():
  rng = np.random.default_rng(2)
  X = rng.random(400).reshape(-1,2)
  X[:,1] = X[:,1] * 4 + 11.5
  X[:,0] = X[:,0] * (285-150) + 150
  Y = np.zeros(len(X))
  i=0
  for t,d in X:
    y = -3/(260-175)*t + 21
    if (t > 175 and t < 260 and d > 12 and d < 15 and d<=y ):
      Y[i] = 1
    else:
      Y[i] = 0
    i += 1

  return (X, Y.reshape(-1,1))

In [3]:
X,Y = load_coffee_data()
X.shape, Y.shape

((200, 2), (200, 1))

In [4]:
norm=tf.keras.layers.Normalization(axis=-1)
norm.adapt(X)
Xn=norm(X)
Xn[:5]

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.8345551, -0.6528792],
       [ 1.0323051, -1.3851453],
       [ 0.3089391,  0.8716251],
       [-1.0835688, -1.5154841],
       [-0.7894313,  0.6194935]], dtype=float32)>

In [8]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [19]:
def Dense(inp,w,b):
  units=w.shape[1]
  a_out=np.zeros(units)
  for i in range(units):
    wi=w[:,i]
    z=np.dot(inp,wi)+b[i]
    a_out[i]=sigmoid(z)
  return (a_out)

In [20]:
def Sequential(x,w1,b1,w2,b2):
  a1=Dense(x,w1,b1)
  a2=Dense(a1,w2,b2)
  return (a2)

In [25]:
def predict(x,w1,b1,w2,b2):
  m=x.shape[0]
  y=np.zeros((m,1))
  for i in range(m):
    y[i,0]=Sequential(x[i],w1,b1,w2,b2)
    if y[i,0]>0.5:
      y[i,0]=(1)
    else:
      y[i,0]=int(0)
  return (y)

In [26]:
x_test=np.array([[200,13.9], [200,17],[200,20]])
xn_test=norm(x_test)
w1=np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
w2=np.array( [[-31.18], [-27.59], [-32.56]] )
b1=np.array( [-9.82, -9.28,  0.96] )
b2=np.array( [15.41] )
y_test=predict(xn_test,w1,b1,w2,b2)
y_test

<ipython-input-25-1e84510feeef>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y[i,0]=Sequential(x[i],w1,b1,w2,b2)


array([[1.],
       [0.],
       [0.]])